" =============================
" NeoBundle
" =============================

" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

" Echo startup time on start
if has('vim_starting') && has('reltime')
  let g:startuptime = reltime()
  augroup vimrc-startuptime
    autocmd! VimEnter * let g:startuptime = reltime(g:startuptime) | redraw
    \ | echomsg 'startuptime: ' . reltimestr(g:startuptime)
  augroup END
endif

if ! isdirectory(expand('~/.vim/bundle'))
    echon "Installing neobundle.vim..."
    silent call mkdir(expand('~/.vim/bundle'), 'p')
    silent !git clone https://github.com/Shougo/neobundle.vim $HOME/.vim/bundle/neobundle.vim
    echo "done."
    if v:shell_error
        echoerr "neobundle.vim installation has failed!"
        finish
    endif
endif

if has('vim_starting')
    if &compatible
    set nocompatible               " Be iMproved
    endif
    " Required:
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!
NeoBundle 'Shougo/unite.vim'

NeoBundle 'Shougo/neomru.vim'
" Shougo/neocomplete
if has('lua') && v:version >= 703
    NeoBundle 'Shougo/neocomplete.vim'
else
    NeoBundle 'Shougo/neocomplcache.vim'
endif

NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'haya14busa/haya14busa-snippets'
NeoBundle 'mattn/emmet-vim'
NeoBundle 'deris/vim-rengbang'
NeoBundle 'deris/vim-visualinc'
NeoBundle 'h1mesuke/vim-alignta'
NeoBundle 'tyru/caw.vim'
NeoBundle 'ujihisa/neco-look'
NeoBundle 'rhysd/vim-grammarous'

" Development
NeoBundle 'thinca/vim-quickrun'
NeoBundle "osyo-manga/vim-watchdogs"
NeoBundle 'koron/codic-vim'
NeoBundle 'rhysd/unite-codic.vim'

" Library
NeoBundle 'Shougo/vimproc', {
  \ 'build' : {
    \ 'windows' : 'make -f make_mingw32.mak',
    \ 'cygwin' : 'make -f make_cygwin.mak',
    \ 'mac' : 'make -f make_mac.mak',
    \ 'unix' : 'make -f make_unix.mak',
  \ },
\ }
NeoBundle 'mattn/webapi-vim'
NeoBundle 'vim-jp/vital.vim'
NeoBundle 'osyo-manga/unite-vital-module'
NeoBundle 'osyo-manga/vital-over'
NeoBundle 'osyo-manga/vital-reunions'
NeoBundle 'osyo-manga/vital-coaster'

" Document
NeoBundle 'thinca/vim-ref'
NeoBundle 'mojako/ref-sources.vim'
NeoBundle 'tokuhirom/jsref'
NeoBundle 'mustardamus/jqapi'
NeoBundle 'soh335/vim-ref-jquery'

" Extend Basic Vim Commands
" Matching
NeoBundle 'matchit.zip'
" Yank
NeoBundle 'LeafCage/yankround.vim'
"NeoBundle 't9md/yankround.vim'

" Undo
NeoBundle 'sjl/gundo.vim'
" Visual mode
NeoBundle 'kana/vim-niceblock'
" Search
NeoBundle 'thinca/vim-visualstar'
NeoBundle 'osyo-manga/vim-anzu'
NeoBundle 'osyo-manga/vim-over'

NeoBundle 'vim-jp/autofmt'

" Motion
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'haya14busa/vim-easyoperator-line'
NeoBundle 'haya14busa/vim-easyoperator-phrase'
NeoBundle 'rhysd/clever-f.vim'
NeoBundle 'rhysd/accelerated-jk'
"NeoBundle 'saihoooooooo/glowshi-ft.vim'
NeoBundle 'haya14busa/incsearch.vim'


" Text Object
NeoBundle 'kana/vim-textobj-user'
NeoBundle 'kana/vim-textobj-entire'           " ae, ie
NeoBundle 'kana/vim-textobj-fold'             " az, iz
NeoBundle 'kana/vim-textobj-indent'           " ai, ii
NeoBundle 'kana/vim-textobj-line'             " al, il
NeoBundle 'kana/vim-textobj-syntax'           " ay, iy
NeoBundle 'kana/vim-textobj-django-template'  " adb, idb
NeoBundle 'thinca/vim-textobj-between'        " af{char}, if{char}
NeoBundle 'mattn/vim-textobj-url'             " au, iu
NeoBundle 'osyo-manga/vim-textobj-multiblock' " ab, ib
NeoBundle 'lucapette/vim-textobj-underscore'  " a_, i_
NeoBundle 'haya14busa/vim-textobj-number'     " an, in
" NeoBundle 'h1mesuke/textobj-wiw'              " a,w a,e

NeoBundle 'wellle/targets.vim'
" NeoBundle 'gcmt/wildfire.vim'
NeoBundle 'tpope/vim-surround'
NeoBundle 'tpope/vim-repeat'

" Operator
NeoBundle 'kana/vim-operator-user'
NeoBundle 'kana/vim-operator-replace'
"NeoBundle 'rhysd/vim-operator-surround'
NeoBundle 'kana/vim-operator-replace', {
            \ 'autoload' : {
            \     'mappings' : '<Plug>(operator-replace)'
            \     }
            \ }

NeoBundle 'rhysd/vim-operator-trailingspace-killer', {
            \ 'autoload' : {
            \     'mappings' : '<Plug>(operator-trailingspace-killer)'
            \     }
            \ }

NeoBundle 'rhysd/vim-operator-filled-with-blank', {
            \ 'autoload' : {
            \     'mappings' : '<Plug>(operator-filled-with-blank)'
            \     }
            \ }

NeoBundle 'rhysd/vim-operator-evalruby', {
            \ 'autoload' : {
            \     'mappings' : '<Plug>(operator-evalruby)'
            \     }
            \ }

NeoBundle 'rhysd/vim-operator-surround', {
            \ 'depends' : 'tpope/vim-repeat',
            \ 'autoload' : {
            \       'mappings' : '<Plug>(operator-surround-'
            \   }
            \ }

NeoBundle 'deris/vim-operator-insert', {
            \ 'autoload' : {
            \   'mappings' : [
            \       '<Plug>(operator-insert-i)',
            \       '<Plug>(operator-insert-a)',
            \   ],
            \   },
            \ }

" Git
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'cohama/agit.vim'
NeoBundle 'mhinz/vim-signify'

NeoBundle 'thinca/vim-openbuf'
NeoBundle 'Shougo/vim-vcs', {
    \ 'depends' : 'thinca/vim-openbuf',
    \ 'autoload' : {'commands' : 'Vcs'},
    \ }

NeoBundle 'rhysd/committia.vim'
NeoBundle 'rdolgushin/gitignore.vim'

" UI
NeoBundle 'itchyny/lightline.vim'
NeoBundle 'Yggdroot/indentLine'
NeoBundle 't9md/vim-quickhl'
NeoBundle 'mattn/disableitalic-vim'

"TODO
NeoBundle 'osyo-manga/vim-automatic', {
    \ 'depends' : [ 'osyo-manga/vim-gift', 'osyo-manga/vim-reunions' ] }

" Utility
" NeoBundle 'kana/vim-submode'
NeoBundle 'thinca/vim-submode', {
    \ 'rev' : 'my-master',
    \ 'name' : 'vim-submode',
    \ }
NeoBundle 'tyru/open-browser.vim'
NeoBundle 'tyru/open-browser-github.vim'
NeoBundle 'thinca/vim-qfreplace'
NeoBundle 'haya14busa/endtagcomment.vim'
NeoBundle 'hrsh7th/vim-trailing-whitespace'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'jistr/vim-nerdtree-tabs'
NeoBundle 'tomtom/tcomment_vim'
NeoBundle 'AnsiEsc.vim'
NeoBundle 'haya14busa/eew.vim'
NeoBundle 'basyura/TweetVim'

" Application
NeoBundle 'itchyny/calendar.vim'
NeoBundle 'itchyny/screensaver.vim'

" Gist
NeoBundle 'lambdalisue/vim-gista', {
    \ 'depends': [
    \    'Shougo/unite.vim',
    \    'tyru/open-browser.vim',
    \]}
let g:gista#github_user = 'snvx'

" Memo
NeoBundle 'mattn/gist-vim'
NeoBundle 'Shougo/junkfile.vim'

" Filetype
NeoBundle 'Shougo/context_filetype.vim'
NeoBundle 'osyo-manga/vim-precious'
let g:markdown_fenced_languages = [
\  'coffee',
\  'css',
\  'erb=eruby',
\  'javascript',
\  'js=javascript',
\  'json=javascript',
\  'ruby',
\  'sass',
\  'xml',
\  'python',
\  'vim',
\]
NeoBundle 'pangloss/vim-javascript'
NeoBundle 'wavded/vim-stylus'
NeoBundle 'hail2u/vim-css3-syntax'
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'othree/html5.vim'
NeoBundle 'plasticboy/vim-markdown'
NeoBundle 'kannokanno/previm'
NeoBundle 'groenewege/vim-less'

" Python
NeoBundle 'davidhalter/jedi-vim'
NeoBundle 'heavenshell/vim-pydocstring'
NeoBundle 'tell-k/vim-autopep8'
NeoBundle 'hynek/vim-python-pep8-indent'
NeoBundle 'mkomitee/vim-gf-python'
NeoBundle 'Valloric/python-indent'

" CoffeeScript

" JavaScript
NeoBundle 'marijnh/tern_for_vim'
NeoBundle 'maksimr/vim-jsbeautify'
NeoBundle 'mattn/jscomplete-vim'

" Scala
NeoBundle 'derekwyatt/vim-scala'
NeoBundle 'derekwyatt/vim-sbt'
NeoBundle 'mdreves/vim-scaladoc'
NeoBundle 'gre/play2vim'

" TypeScript
NeoBundle 'dmitry-ilyashevich/vim-typescript'
NeoBundle 'leafgarland/typescript-vim'
NeoBundle 'clausreinke/typescript-tools.git'

" Ruby
NeoBundle 'vim-ruby/vim-ruby'
NeoBundle 'joker1007/vim-ruby-heredoc-syntax'
NeoBundle 'tpope/vim-endwise'
NeoBundle 'tpope/vim-rails'
NeoBundleLazy 'supermomonga/neocomplete-rsense.vim', { 'autoload' : {
  \ 'insert' : 1,
  \ 'filetypes': 'ruby',
  \ }}

" .や::を入力したときにオムニ補完が有効になるようにする
if !exists('g:neocomplete#force_omni_input_patterns')
  let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'

" 環境変数RSENSE_HOMEに'/usr/local/bin/rsense'を指定しても動く
let g:neocomplete#sources#rsense#home_directory = '/usr/local/bin/rsense'

" Less
NeoBundle 'less.vim'

" scss
NeoBundle 'cakebaker/scss-syntax.vim'

" node.js
NeoBundle 'myhere/vim-nodejs-complete'
NeoBundle 'felixge/vim-nodejs-errorformat'
NeoBundle 'moll/vim-node'

" Scheme
NeoBundle 'aharisu/vim_goshrepl'
NeoBundle 'kien/rainbow_parentheses.vim'


" Fold
"NeoBundle 'LeafCage/foldCC'
NeoBundle 'tmhedberg/SimpylFold' "for Python
NeoBundle 'vim-scripts/CSS-one-line--multi-line-folding'

" Japanese
NeoBundle 'vim-jp/vimdoc-ja'
" NeoBundle 'tyru/skk.vim'

" ColorScheme
NeoBundle 'tomasr/molokai'
NeoBundle 'sickill/vim-monokai'
NeoBundle 'vim-scripts/Wombat'
NeoBundle 'altercation/vim-colors-solarized'
NeoBundle 'nanotech/jellybeans.vim'
NeoBundle 'w0ng/vim-hybrid'
NeoBundle 'vim-scripts/twilight'
NeoBundle 'jonathanfilip/vim-lucius'
NeoBundle 'jpo/vim-railscasts-theme'
NeoBundle 'vim-scripts/rdark'
NeoBundle 'djjcast/mirodark'
NeoBundle 'sjl/badwolf'
NeoBundle 'cocopon/iceberg.vim'
NeoBundle 'reedes/vim-colors-pencil'

" Vim script
NeoBundle 'mattn/learn-vimscript'
NeoBundle 'thinca/vim-prettyprint'
NeoBundle 'tyru/capture.vim'
NeoBundle 'kana/vim-vspec'
NeoBundle 'thinca/vim-themis'
NeoBundle 'thinca/vim-editvar'
NeoBundle 'tyru/restart.vim'
NeoBundle 'thinca/vim-ft-help_fold', {
    \ 'filetypes' : 'help'
    \ }
NeoBundle 'syngan/vim-vimlint', {
    \ 'depends' : 'ynkdir/vim-vimlparser'}
NeoBundle 'thinca/vim-localrc'

" Others
NeoBundle 'basyura/TweetVim'
NeoBundle 'basyura/twibill.vim'
NeoBundle 'basyura/J6uil.vim'
NeoBundle 'dogrover/vim-pentadactyl'
NeoBundle 'supermomonga/thingspast.vim'
NeoBundle 'rbtnn/puyo.vim'
NeoBundle 'thinca/vim-scouter'

NeoBundle 'thinca/vim-threes'
" NeoBundle 'tpope/vim-rake'
NeoBundle 'mattn/flappyvird-vim'
NeoBundle 'mattn/yamada2-vim'
NeoBundle 'rizzatti/dash.vim'

" Plugins
"NeoBundle 'osyo-manga/vim-brightest'
"NeoBundle 'eagletmt/ghci-vim'
"NeoBundle 'eagletmt/ghcmod-vim'
"NeoBundle 'cohama/vim-exchange'
"NeoBundle 'cohama/vim-insert-linenr'
"NeoBundle 'maxbrunsfeld/vim-yankstack'
"NeoBundle 'visualmark.vim'
"NeoBundle 'airblade/vim-gitgutter'
"NeoBundle 'ShowMarks'
"NeoBundle 'kien/ctrlp.vim'
"NeoBundle 'YankRing.vim'
"NeoBundle 'sgur/vim-gutter'
" ======================
NeoBundle 'kana/vim-fakeclip'
NeoBundle 'jacquesbh/vim-showmarks'
NeoBundle 'Lokaltog/vim-powerline'
NeoBundle 'tacroe/unite-mark'
NeoBundle 'deris/columnjump'
NeoBundle 't9md/vim-textmanip'
NeoBundle 't9md/vim-choosewin'
NeoBundle 'deris/vim-cmdline-switch'
NeoBundle 'taglist.vim'
NeoBundle 'yonchu/accelerated-smooth-scroll'
NeoBundle 'syui/airsave.vim'
NeoBundle 'cohama/lexima.vim'
NeoBundle 'deris/vim-shot-f'
NeoBundle 'tmhedberg/matchit'
NeoBundle 'elzr/vim-json'
NeoBundle 'terryma/vim-multiple-cursors'
NeoBundle 'koron/codic-vim'
"NeoBundle 'syui/tweetvim_notfiy'
NeoBundle 'slim-template/vim-slim'
NeoBundle 'gist:rhysd/4201877', {
\   'name': 'tweetvim_update',
\   'script_type': 'plugin'
\}


call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck





"================================================================================
"================================================================================
    " ======================
    "NeoBundle '2072/PHP-Indenting-for-VIm'
    "NeoBundle '29decibel/codeschool-vim-theme'
    "NeoBundle '5t111111/alt-gtags.vim'
    "NeoBundle '5t111111/markdown-preview.vim'
    "NeoBundle '5t111111/neat-json.vim'
    "NeoBundle 'Align'
    "NeoBundle 'AndrewRadev/inline_edit.vim'
    "NeoBundle 'AndrewRadev/multichange.vim'
    "NeoBundle 'AndrewRadev/splitjoin.vim'
    "NeoBundle 'AndrewRadev/switch.vim'
    "NeoBundle 'AndrewRadev/vim-coffee-script'
    "NeoBundle 'Arduino-syntax-file'
    "NeoBundle 'AtsushiM/RetinaResize'
    "NeoBundle 'AtsushiM/auto-make.vim'
    "NeoBundle 'AtsushiM/jasmine-helper.vim'
    "NeoBundle 'AutoClose'
    "NeoBundle 'Blackrush/vim-gocode'
    "NeoBundle 'CD.vim'
    "NeoBundle 'CSApprox'
    "NeoBundle 'ChrisYip/Better-CSS-Syntax-for-Vim'
    "NeoBundle 'Conque-Shell'
    "NeoBundle 'Decho'
    "NeoBundle 'DirDiff.vim'
    "NeoBundle 'DrawIt'
    "NeoBundle 'EasyGrep'
    "NeoBundle 'EasyMotion'
    "NeoBundle 'Erlang-plugin-package'
    "NeoBundle 'FSwitch'
    "NeoBundle 'FuzzyFinder'
    "NeoBundle 'Glench/Vim-Jinja2-Syntax'
    "NeoBundle 'Gundo'
    "NeoBundle 'HTML5-Syntax-File'
    "NeoBundle 'Indent-Guides'
    "NeoBundle 'IndexedSearch'
    "NeoBundle 'JNRowe/vim-jnrowe'
    "NeoBundle 'JSON.vim'
    "NeoBundle 'JavaScript-syntax'
    "NeoBundle 'Javascript-syntax'
    "NeoBundle 'JazzCore/neocomplcache-ultisnips'
    "NeoBundle 'JesseKPhillips/d.vim'
    "NeoBundle 'JulesWang/css.vim'
    "NeoBundle 'KazuakiM/vim-qfsigns'
    "NeoBundle 'Keithbsmiley/rspec.vim'
    "NeoBundle 'L9'
    "NeoBundle 'LaTeX-Box-Team/LaTeX-Box'
    "NeoBundle 'LargeFile'
    "NeoBundle 'LeafCage/foldCC'
    "NeoBundle 'LeafCage/revolver.vim'
    "NeoBundle 'LeafCage/yankround.vim'
    "NeoBundle 'Lokaltog/powerline'
    "NeoBundle 'Lokaltog/powerline-fonts'
    "NeoBundle 'Lokaltog/vim-distinguished'
    "NeoBundle 'Lokaltog/vim-easymotion'
    "NeoBundle 'Lokaltog/vim-powerline'
    "NeoBundle 'Mark'
    "NeoBundle 'Markdown'
    "NeoBundle 'MaxSt/FlatColor'
    "NeoBundle 'Mustang2'
    "NeoBundle 'OmniCppComplete'
    "NeoBundle 'PProvost/vim-ps1'
    "NeoBundle 'Puppet-Syntax-Highlighting'
    "NeoBundle 'Pychimp/vim-luna'
    "NeoBundle 'Pychimp/vim-sol'
    "NeoBundle 'QFixHowm'
    "NeoBundle 'Quich-Filter'
    "NeoBundle 'QuickBuf'
    "NeoBundle 'Raimondi/delimitMate'
    "NeoBundle 'Rename'
    "NeoBundle 'Rip-Rip/clang_complete'
    "NeoBundle 'RubySinatra'
    "NeoBundle 'Rykka/ColorV'
    "NeoBundle 'Rykka/easydigraph.vim'
    "NeoBundle 'Rykka/lastbuf.vim'
    "NeoBundle 'Rykka/vim-galaxy'
    "NeoBundle 'SQLComplete.vim'
    "NeoBundle 'SQLUtilities'
    "
    "NeoBundle 'Shougo/echodoc'
    "NeoBundle 'Shougo/junkfile.vim'
    "NeoBundle 'Shougo/neobundle-vim-scripts'
    "NeoBundle 'Shougo/neobundle.vim'
    "NeoBundle 'Shougo/neocomplcache'
    "NeoBundle 'Shougo/neocomplcache-clang'
    "NeoBundle 'Shougo/neocomplcache-rsense'
    "NeoBundle 'Shougo/neocomplcache-rsense.vim'
    "NeoBundle 'Shougo/neocomplcache-snippets-complete'
    "NeoBundle 'Shougo/neocomplcache.vim'
    "NeoBundle 'Shougo/neocomplete'
    "NeoBundle 'Shougo/neomru.vim'
    "NeoBundle 'Shougo/neosnippet'
    "NeoBundle 'Shougo/neosnippet-snippets'
    "NeoBundle 'Shougo/unite-build'
    "NeoBundle 'Shougo/unite-help'
    "NeoBundle 'Shougo/unite-outline'
    "NeoBundle 'Shougo/unite-session'
    "NeoBundle 'Shougo/unite-ssh'
    "NeoBundle 'Shougo/unite-sudo'
    "NeoBundle 'Shougo/unite.vim'
    "NeoBundle 'Shougo/vesting'
    "NeoBundle 'Shougo/vimfiler'
    "NeoBundle 'Shougo/vimproc'
    "NeoBundle 'Shougo/vimshell'
    "NeoBundle 'Shougo/vinarise'
    "NeoBundle 'ShowMarks7'
    "NeoBundle 'Simple-Javascript-Indenter'
    "NeoBundle 'SirVer/ultisnips'
    "NeoBundle 'Sixeight/unite-grep'
    "NeoBundle 'Smooth-Scroll'
    "NeoBundle 'Solarized'
    "NeoBundle 'Source-Explorer-srcexpl.vim'
    "NeoBundle 'StanAngeloff/php.vim'
    "NeoBundle 'SudoEdit.vim'
    "NeoBundle 'Syntastic'
    "NeoBundle 'SyntaxComplete'
    "NeoBundle 'Tabular'
    "NeoBundle 'TaskList.vim'
    "NeoBundle 'The-NERD-Commenter'
    "NeoBundle 'The-NERD-tree'
    "NeoBundle 'Toggle'
    "NeoBundle 'Townk/vim-autoclose'
    "NeoBundle 'TwitVim'
    "NeoBundle 'VST'
    "NeoBundle 'Valloric/ListToggle'
    "NeoBundle 'Valloric/MatchTagAlways'
    "NeoBundle 'Valloric/Vim-Jinja2-Syntax'
    "NeoBundle 'Valloric/YouCompleteMe'
    "NeoBundle 'Valloric/vim-indent-guides'
    "NeoBundle 'Valloric/vim-instant-markdown'
    "NeoBundle 'Valloric/vim-operator-highlight'
    "NeoBundle 'Valloric/vim-valloric-colorscheme'
    "NeoBundle 'Valloric/xmledit'
    "NeoBundle 'ViewOutput'
    "NeoBundle 'Vim-LaTeX'
    "NeoBundle 'VimCalc'
    "NeoBundle 'VimClojure'
    "NeoBundle 'Wise/darkburn.vim'
    "NeoBundle 'Wombat'
    "NeoBundle 'YankRing.vim'
    "NeoBundle 'Yggdroot/indentLine'
    "NeoBundle 'a.vim'
    "NeoBundle 'ack.vim'
    "NeoBundle 'acustodioo/vim-tmux'
    "NeoBundle 'adinapoli/vim-markmultiple'
    "NeoBundle 'agate/vim-align'
    "NeoBundle 'aharisu/vim-gdev'
    "NeoBundle 'aharisu/vim_goshrepl'
    "NeoBundle 'airblade/vim-rooter'
    "NeoBundle 'airblade/vimgutter'
    "NeoBundle 'ajh17/VimCompletesMe'
    "NeoBundle 'akiomik-gutter-vim'
    "NeoBundle 'akiyan/vim-textobj-php'
    "NeoBundle 'akiyan/vim-textobj-xml-attribute'
    "NeoBundle 'aklt/plantuml-syntax'
    "NeoBundle 'aktau/vim-easytags'
    "NeoBundle 'alfredodeza/pytest.vim'
    "NeoBundle 'alpaca-tc/alpaca_tags'
    "NeoBundle 'alpaca-tc/lang-8.vim'
    "NeoBundle 'alpaca-tc/neorspec.vim'
    "NeoBundle 'alpaca-tc/vim-endwise'
    "NeoBundle 'alpaca-tc/vim-rsense'
    "NeoBundle 'altercation/vim-colors-solarized'
    "NeoBundle 'amdt/vim-niji'
    "NeoBundle 'anyakichi/vim-surround'
    "NeoBundle 'anyakichi/vim-textobj-ifdef'
    "NeoBundle 'anyakichi/vim-textobj-xbrackets'
    "NeoBundle 'ap/vim-css-color'
    "NeoBundle 'arnau/teaspoon.vim'
    "NeoBundle 'ataraxer/sapphire256.vim'
    "NeoBundle 'atelierbram/vim-colors_atelier-schemes'
    "NeoBundle 'autodate.vim'
    "NeoBundle 'baskerville/bubblegum'
    "NeoBundle 'basyura/J6uil.vim'
    "NeoBundle 'basyura/TweetVim'
    "NeoBundle 'basyura/bitly.vim'
    "NeoBundle 'basyura/jslint.vim'
    "NeoBundle 'basyura/twibill.vim'
    "NeoBundle 'basyura/unite-rails'
    "NeoBundle 'basyura/unite-twitter'
    "NeoBundle 'basyura/unite-yarm'
    "NeoBundle 'basyura/webapi-vim'
    "NeoBundle 'beardedprojamz/vim-colors-blayden'
    "NeoBundle 'benmills/vimux'
    "NeoBundle 'bigfish/vim-js-context-coloring'
    "NeoBundle 'bitc/vim-bad-whitespace'
    "NeoBundle 'bkad/CamelCaseMotion'
    "NeoBundle 'bling/vim-airline'
    "NeoBundle 'bling/vim-bufferline'
    "NeoBundle 'bluecloud'
    "NeoBundle 'bluntpeak/bluntpeak-vim-colors'
    "NeoBundle 'bohrshaw/vim-vimperator-syntax'
    "NeoBundle 'boolfool/unite-perlbrew'
    "NeoBundle 'bootleq/ShowMarks'
    "NeoBundle 'bronzehedwick/impactjs-colorscheme'
    "NeoBundle 'bufexplorer.zip'
    "NeoBundle 'bufkill.vim'
    "NeoBundle 'c9s/perlomni.vim'
    "NeoBundle 'candy.vim'
    "NeoBundle 'capslock.vim'
    "NeoBundle 'carlosvillu/coffeScript-VIM-Snippets'
    "NeoBundle 'cespare/vim-toml'
    "NeoBundle 'chaquotay/ftl-vim-syntax'
    "NeoBundle 'chase/vim-ansible-yaml'
    "NeoBundle 'chenkaie/DirDiff.vim'
    "NeoBundle 'chenkaie/smarthomekey.vim'
    "NeoBundle 'chibicode/CRDispatcher'
    "NeoBundle 'chibicode/dwm.vim'
    "NeoBundle 'chikatoike/concealedyank.vim'
    "NeoBundle 'chmllr/elrodeo-colorscheme'
    "NeoBundle 'choplin/unite-spotlight'
    "NeoBundle 'choplin/unite-vim_hacks'
    "NeoBundle 'chrisba/csv.vim'
    "NeoBundle 'chrisbra/NrrwRgn'
    "NeoBundle 'chrisbra/color_highlight'
    "NeoBundle 'chriskempson/base16-vim'
    "NeoBundle 'chriskempson/tomorrow-theme'
    "NeoBundle 'chriskempson/vim-tomorrow-theme'
    "NeoBundle 'ciaranm/detectindent'
    "NeoBundle 'ciaranm/inkpot'
    "NeoBundle 'claco/jasmine.vim'
    "NeoBundle 'clang-complete'
    "NeoBundle 'closetag.vim'
    "NeoBundle 'cocopon/iceberg.vim'
    "NeoBundle 'cocopon/lightline-hybrid.vim'
    "NeoBundle 'coderifous/textobj-word-column.vim'
    "NeoBundle 'cohama/.vim'
    "NeoBundle 'cohama/rsense'
    "NeoBundle 'cohama/vim-hier'
    "NeoBundle 'cohama/vim-javascript'
    "NeoBundle 'colorizer'
    "NeoBundle 'command-t'
    "NeoBundle 'coot/cmdalias_vim'
    "NeoBundle 'csexton/jekyll.vim'
    "NeoBundle 'csexton/spacemanspiff.vim'
    "NeoBundle 'css_color.vim'
    "NeoBundle 'csscomb/csscomb-for-vim'
    "NeoBundle 'ctags.vim'
    "NeoBundle 'ctrlp.vim'
    "NeoBundle 'dag/vim2hs'
    "NeoBundle 'dahu/vim-fanfingtastic'
    "NeoBundle 'daisuzu/rainbowcyclone.vim'
    "NeoBundle 'daisuzu/translategoogle.vim'
    "NeoBundle 'daltoad/vim-jade'
    "NeoBundle 'dannyob/quickfixstatus'
    "NeoBundle 'danro/rename.vim'
    "NeoBundle 'davidhalter/jedi-vim'
    "NeoBundle 'davidoc/taskpaper.vim'
    "NeoBundle 'daylerees/colour-schemes'
    "NeoBundle 'daylilyfield/sexyscroll.vim'
    "NeoBundle 'dbakker/vim-md-noerror'
    "NeoBundle 'dbakker/vim-paragraph-motion'
    "NeoBundle 'dbb/vim-gummybears-colorscheme'
    "NeoBundle 'dbext.vim'
    "NeoBundle 'delimitMate.vim'
    "NeoBundle 'derekwyatt/vim-scala'
    "NeoBundle 'deris/columnjump'
    "NeoBundle 'deris/molokai'
    "NeoBundle 'deris/parajump'
    "NeoBundle 'deris/vim-duzzle'
    "NeoBundle 'deris/vim-loadafterft'
    "NeoBundle 'deris/vim-rengbang'
    "NeoBundle 'deris/vim-textobj-enclosedsyntax'
    "NeoBundle 'deris/vim-textobj-headwordofline'
    "NeoBundle 'deris/vim-wombat'
    "NeoBundle 'dgryski/vim-godef'
    "NeoBundle 'divad12/sparkup'
    "NeoBundle 'djjcast/mirodark'
    "NeoBundle 'dln/avro-vim'
    "NeoBundle 'dsummers/gundo.vim'
    "NeoBundle 'dsummersl/svntools'
    "NeoBundle 'dsummersl/vim-cdo'
    "NeoBundle 'dsummersl/vim-sluice'
    "NeoBundle 'dsummersl/vim-utf2ascii'
    "NeoBundle 'dsummersl/vimunit'
    "NeoBundle 'dsummersl/vus'
    "NeoBundle 'dsummersl/wikia-csv'
    "NeoBundle 'dyng/ctrlsf.vim'
    "NeoBundle 'eagletmt/neco-ghc'
    "NeoBundle 'eagletmt/unite-haddock'
    "NeoBundle 'earendel'
    "NeoBundle 'ebnf.vim'
    "NeoBundle 'eccyan/vim-rspec'
    "NeoBundle 'editorconfig/editorconfig-vim'
    "NeoBundle 'edsono/vim-matchit'
    "NeoBundle 'elzr/vim-json'
    "NeoBundle 'emonkak/vim-operator-comment'
    "NeoBundle 'emonkak/vim-operator-sort'
    "NeoBundle 'endel/flashdevelop.vim'
    "NeoBundle 'endel/vimhub-colorscheme'
    "NeoBundle 'endwise.vim'
    "NeoBundle 'eraserhd/vim-ios'
    "NeoBundle 'ercolanelli-leo/candyVirus'
    "NeoBundle 'eregex.vim'
    "NeoBundle 'errormarker.vim'
    "NeoBundle 'ervandew/ag'
    "NeoBundle 'ervandew/supertab'
    "NeoBundle 'evanmiller/nginx-vim-syntax'
    "NeoBundle 'evidens/vim-twig'
    "NeoBundle 'exe NeoBundle '
    "NeoBundle 'express.vim'
    "NeoBundle 'exu/pgsql.vim'
    "NeoBundle 'fatih/vim-go'
    "NeoBundle 'felixr/vim-multiedit'
    "NeoBundle 'fholgado/minibufexpl.vim'
    "NeoBundle 'fkfk/rbpit.vim'
    "NeoBundle 'flxf/uCpp.vim'
    "NeoBundle 'frah/monday'
    "NeoBundle 'ftzeng/futora'
    "NeoBundle 'fuenor/JpFormat.vim'
    "NeoBundle 'fuenor/im_control.vim'
    "NeoBundle 'fuenor/qfixgrep'
    "NeoBundle 'fuenor/qfixhowm'
    "NeoBundle 'gShougo/vimproc'
    "NeoBundle 'gShougo/vimshell'
    "NeoBundle 'galpaca-tc/alpaca_tags'
    "NeoBundle 'gaving/vim-textobj-argument'
    "NeoBundle 'gcmt/breeze.vim'
    "NeoBundle 'gcmt/wildfire.vim'
    "NeoBundle 'ghail2u/vim-css3-syntax'
    "NeoBundle 'ghokaccha/vim-html5validator'
    "NeoBundle 'glidenote/memolist.vim'
    "NeoBundle 'glidenote/nogistub.vim'
    "NeoBundle 'glidenote/octoeditor.vim'
    "NeoBundle 'glidenote/serverspec-snippets'
    "NeoBundle 'gmarik/vundle'
    "NeoBundle 'godlygeek/csapprox'
    "NeoBundle 'godlygeek/tabular'
    "NeoBundle 'goldfeld/vim-seek'
    "NeoBundle 'gothree/html5.vim'
    "NeoBundle 'gregsexton/MatchTag'
    "NeoBundle 'gregsexton/VimCalc'
    "NeoBundle 'gregsextonv'
    "NeoBundle 'grep.vim'
    "NeoBundle 'grhysd/clever-f.vim'
    "NeoBundle 'groenewege/vim-less'
    "NeoBundle 'gscrooloose/syntastic'
    "NeoBundle 'gthinca/vim-ref'
    "NeoBundle 'gthoughtbot/vim-rspec'
    "NeoBundle 'gtpope/vim-dispatch'
    "NeoBundle 'guicolorscheme.vim'
    "NeoBundle 'guns/ultisnips'
    "NeoBundle 'guns/vim-clojure-static'
    "NeoBundle 'guns/xterm-color-table.vim'
    "NeoBundle 'gvim-scripts/AutoComplPop'
    "NeoBundle 'gvim-scripts/dbext.vim'
    "NeoBundle 'gyuku-t/vim-ref-ri'
    "NeoBundle 'h1mesuke/textobj-wiw'
    "NeoBundle 'h1mesuke/unite-outline'
    "NeoBundle 'h1mesuke/vim-alignta'
    "NeoBundle 'h1mesuke/vim-benchmark'
    "NeoBundle 'hail2u/h2u_colorscheme'
    "NeoBundle 'hail2u/vim-css3-syntax'
    "NeoBundle 'hallettj/jslint.vim'
    "NeoBundle 'hallison/vim-markdown'
    "NeoBundle 'hallison/vim-ruby-sinatra'
    "NeoBundle 'haskell.vim'
    "NeoBundle 'haxe.vim'
    "NeoBundle 'haya14busa-snippets'
    "NeoBundle 'haya14busa/vim-migemo'
    "NeoBundle 'heavenshell/vim-jsdoc'
    "NeoBundle 'heavenshell/vim-quickrun-hook-unittest'
    "NeoBundle 'hekyou/vim-rectinsert'
    "NeoBundle 'helino/vim-json'
    "NeoBundle 'hewes/unite-gtags'
    "NeoBundle 'hickop/vim-hickop-colors'
    "NeoBundle 'hlissner/vim-multiedit'
    "NeoBundle 'hmaarrfk/vim-colors-solarized'
    "NeoBundle 'hokaccha/vim-html5validator'
    "NeoBundle 'hokaccha/vim-ref'
    "NeoBundle 'honza/dockerfile.vim'
    "NeoBundle 'honza/vim-snippets'
    "NeoBundle 'hotchpotch/perldoc-vim'
    "NeoBundle 'houtsnip/vim-emacscommandline'
    "NeoBundle 'hrsh7th/unite-mark'
    "NeoBundle 'hrsh7th/unite-todo'
    "NeoBundle 'hrsh7th/vim-better-css-indent'
    "NeoBundle 'hrsh7th/vim-hybrid'
    "NeoBundle 'hrsh7th/vim-neco-calc'
    "NeoBundle 'hrsh7th/vim-neco-snippets'
    "NeoBundle 'hrsh7th/vim-trailing-whitespace'
    "NeoBundle 'hrsh7th/vim-unite-vcs'
    "NeoBundle 'hrsh7th/vim-versions'
    "NeoBundle 'html5.vim'
    "NeoBundle 'hynek/vim-python-pep8-indent'
    "NeoBundle 'idanarye/vim-merginal'
    "NeoBundle 'inkarkat/closetag.vim'
    "NeoBundle 'itchyny/calendar.vim'
    "NeoBundle 'itchyny/landscape.vim'
    "NeoBundle 'itchyny/lightline.vim'
    "NeoBundle 'itchyny/thumbnail.vim'
    "NeoBundle 'itspriddle/vim-javascript-indent'
    "NeoBundle 'ivalkeen/vim-simpledb'
    "NeoBundle 'ivyl/vim-bling'
    "NeoBundle 'jQuery'
    "NeoBundle 'jade.vim'
    "NeoBundle 'januswel/autotmpl.vim'
    "NeoBundle 'januswel/html5.vim'
    "NeoBundle 'januswel/jwlib'
    "NeoBundle 'jaxbothub-issues.vim'
    "NeoBundle 'jceb/vim-editqf'
    "NeoBundle 'jceb/vim-hier'
    "NeoBundle 'jceb/vim-orgmode'
    "NeoBundle 'jcommenter.vim'
    "NeoBundle 'jelera/vim-gummybears-colorscheme'
    "NeoBundle 'jelera/vim-javascript-syntax'
    "NeoBundle 'jeroenbourgois/vim-actionscript'
    "NeoBundle 'jiangmiao/auto-pairs'
    "NeoBundle 'jiangmiao/simple-javascript-indenter'
    "NeoBundle 'jimsei/winresizer'
    "NeoBundle 'jmcantrell/vim-virtualenv'
    "NeoBundle 'jnurmine/Zenburn'
    "NeoBundle 'jnwhiteh/vim-golang'
    "NeoBundle 'joedicastro/vim-molokai256'
    "NeoBundle 'john2x/flatui.vim'
    "NeoBundle 'joker1007/quickrun-rspec-notifier'
    "NeoBundle 'joker1007/unite-pull-request'
    "NeoBundle 'joker1007/vim-markdown-quote-syntax'
    "NeoBundle 'joker1007/vim-metarw-qiita'
    "NeoBundle 'joker1007/vim-metarwhub-issues'
    "NeoBundle 'jonathanfilip/vim-lucius'
    "NeoBundle 'joonty/vdebug'
    "NeoBundle 'jpalardy/vim-slime'
    "NeoBundle 'jpformat'
    "NeoBundle 'jpo/vim-railscasts-theme'
    "NeoBundle 'jsx/JSX'
    "NeoBundle 'jsx/jsx.vim'
    "NeoBundle 'jtratner/vim-flavored-markdown'
    "NeoBundle 'junegunn/goyo.vim'
    "NeoBundle 'junegunn/seoul256.vim'
    "NeoBundle 'junegunn/vader.vim'
    "NeoBundle 'junegunn/vim-easy-align'
    "NeoBundle 'justinmk/TextObjectify'
    "NeoBundle 'justinmk/vim-gtfo'
    "NeoBundle 'justinmk/vim-ipmotion'
    "NeoBundle 'justinmk/vim-sneak'
    "NeoBundle 'juvenn/mustache.vim'
    "NeoBundle 'jwhitley/vim-matchit'
    "NeoBundle 'kakkyz81/evervim'
    "NeoBundle 'kana/vim-advice'
    "NeoBundle 'kana/vim-altercmd'
    "NeoBundle 'kana/vim-altr'
    "NeoBundle 'kana/vim-arpeggio'
    "NeoBundle 'kana/vim-fakeclip'
    "NeoBundle 'kana/vim-filetype-haskell'
    "NeoBundle 'kana/vim-gf-user'
    "NeoBundle 'kana/vim-grex'
    "NeoBundle 'kana/vim-metarw'
    "NeoBundle 'kana/vim-narrow'
    "NeoBundle 'kana/vim-niceblock'
    "NeoBundle 'kana/vim-operator-replace'
    "NeoBundle 'kana/vim-operator-user'
    "NeoBundle 'kana/vim-repeat'
    "NeoBundle 'kana/vim-scratch'
    "NeoBundle 'kana/vim-smartchr'
    "NeoBundle 'kana/vim-smartinput'
    "NeoBundle 'kana/vim-smarttill'
    "NeoBundle 'kana/vim-smartword'
    "NeoBundle 'kana/vim-submode'
    "NeoBundle 'kana/vim-surround'
    "NeoBundle 'kana/vim-tabpagecd'
    "NeoBundle 'kana/vim-textobj-entire'
    "NeoBundle 'kana/vim-textobj-fold'
    "NeoBundle 'kana/vim-textobj-function'
    "NeoBundle 'kana/vim-textobj-help'
    "NeoBundle 'kana/vim-textobj-indent'
    "NeoBundle 'kana/vim-textobj-jabraces'
    "NeoBundle 'kana/vim-textobj-lastpat'
    "NeoBundle 'kana/vim-textobj-line'
    "NeoBundle 'kana/vim-textobj-syntax'
    "NeoBundle 'kana/vim-textobj-underscore'
    "NeoBundle 'kana/vim-textobj-user'
    "NeoBundle 'kana/vim-vspec'
    "NeoBundle 'kannokanno/previm'
    "NeoBundle 'kannokanno/unite-todo'
    "NeoBundle 'kchmck/vim-coffee-script'
    "NeoBundle 'kepbod/php_indent'
    "NeoBundle 'kevinw/pyflakes-vim'
    "NeoBundle 'kien/ctrlp.vim'
    "NeoBundle 'kien/rainbow_parentheses.vim'
    "NeoBundle 'kingbin/vim-arduino'
    "NeoBundle 'kiudee/greymeans'
    "NeoBundle 'kmnk/vim-unitei'
    "NeoBundle 'koara-local/next-alter.vim'
    "NeoBundle 'koron/chalice'
    "NeoBundle 'koron/codic-vim'
    "NeoBundle 'koron/dicwin-vim'
    "NeoBundle 'koron/imcsc-vim'
    "NeoBundle 'koron/java-helper-vim'
    "NeoBundle 'koron/nyancat-vim'
    "NeoBundle 'kris89/vim-multiple-cursors'
    "NeoBundle 'kshenoy/vim-signature'
    "NeoBundle 'l9.vim'
    "NeoBundle 'leafo/moonscript-vim'
    "NeoBundle 'leshill/vim-json'
    "NeoBundle 'lilydjwg/colorizer'
    "NeoBundle 'lilydjwg/csspretty.vim'
    "NeoBundle 'lucapette/vim-textobj-underscore'
    "NeoBundle 'luochen1990/rainbow'
    "NeoBundle 'luochen1990/select-and-search'
    "NeoBundle 'lyokha/vim-publish-helper'
    "NeoBundle 'mackee/unite-httpstatus'
    "NeoBundle 'majutsushi/tagbar'
    "NeoBundle 'maksimr/vim-jsbeautify'
    "NeoBundle 'maksimr/vim-translator'
    "NeoBundle 'malclocke/vim-buster'
    "NeoBundle 'marijnh/tern'
    "NeoBundle 'marijnh/tern_for_vim'
    "NeoBundle 'matchit.vim'
    "NeoBundle 'matchit.zip'
    "NeoBundle 'matrix.vim--Yang'
    "NeoBundle 'matthias-guenther/hammer.vim'
    "NeoBundle 'mattn/asyncgrep-vim'
    "NeoBundle 'mattn/benchvimrc-vim'
    "NeoBundle 'mattn/calendar-vim'
    "NeoBundle 'mattn/ctrlp-launcher'
    "NeoBundle 'mattn/ctrlp-rebuildfm'
    "NeoBundle 'mattn/emmet-vim'
    "NeoBundle 'mattn/emoji-vim'
    "NeoBundle 'mattn/excitetranslate-vim'
    "NeoBundle 'mattn/favstar-vim'
    "NeoBundle 'mattn/gist-vim'
    "NeoBundle 'mattn/habatobi-vim'
    "NeoBundle 'mattn/hahhah-vim'
    "NeoBundle 'mattn/httpstatus-vim'
    "NeoBundle 'mattn/invader-vim'
    "NeoBundle 'mattn/learn-vimscript'
    "NeoBundle 'mattn/libcallex-vim'
    "NeoBundle 'mattn/mahjong-vim'
    "NeoBundle 'mattn/mkdpreview-vim'
    "NeoBundle 'mattn/multi-vim'
    "NeoBundle 'mattn/perlvalidate-vim'
    "NeoBundle 'mattn/qiita-vim'
    "NeoBundle 'mattn/quickrunex-vim'
    "NeoBundle 'mattn/sonictemplate-vim'
    "NeoBundle 'mattn/unite-advent_calendar'
    "NeoBundle 'mattn/unite-gist'
    "NeoBundle 'mattn/unite-mcdonalds-vim'
    "NeoBundle 'mattn/unite-mpc'
    "NeoBundle 'mattn/unite-nyancat'
    "NeoBundle 'mattn/unite-remotefile'
    "NeoBundle 'mattn/unite-rhythmbox'
    "NeoBundle 'mattn/vdbi-vim'
    "NeoBundle 'mattn/vim-textobj-url'
    "NeoBundle 'mattn/vimplenote-vim'
    "NeoBundle 'mattn/webapi-vim'
    "NeoBundle 'mattn/wiseman-f-vim'
    "NeoBundle 'mattn/wwwrenderer-vim'
    "NeoBundle 'mattn/zencoding-vim'
    "NeoBundle 'matze/vim-move'
    "NeoBundle 'maxbrunsfeld/vim-yankstack'
    "NeoBundle 'mbbill/undotree'
    "NeoBundle 'mfumi/lightsout.vim'
    "NeoBundle 'mfumi/ref-dicts-en'
    "NeoBundle 'mfumi/snake.vim'
    "NeoBundle 'mfumi/unite-mpc'
    "NeoBundle 'mfumi/viminesweeper'
    "NeoBundle 'mhinz/vim-signify'
    "NeoBundle 'mhinz/vim-startify'
    "NeoBundle 'michaeljsmith/vim-indent-object'
    "NeoBundle 'michalbachowski/vim-wombat256mod'
    "NeoBundle 'mikewest/vimroom'
    "NeoBundle 'mileszs/ack.vim'
    "NeoBundle 'milkypostman/vim-togglelist'
    "NeoBundle 'minibufexpl.vim'
    "NeoBundle 'mitechie/pyflakes-pathogen'
    "NeoBundle 'miyakogi/slateblue.vim'
    "NeoBundle 'mklabs/grunt.vim'
    "NeoBundle 'mkomitee/vim-gf-python'
    "NeoBundle 'mlp.vim'
    "NeoBundle 'modsound/macdict-vim'
    "NeoBundle 'mojako/ref-sources.vim'
    "NeoBundle 'moll/vim-bbye'
    "NeoBundle 'molokai'
    "NeoBundle 'monday'
    "NeoBundle 'monochromegane/unite-yaml'
    "NeoBundle 'mopp/AOJ.vim'
    "NeoBundle 'mopp/rogue.vim'
    "NeoBundle 'mopp/unite-rss'
    "NeoBundle 'morhetz/gruvbox'
    "NeoBundle 'moro/unite-stepdefs'
    "NeoBundle 'moro/vim-review'
    "NeoBundle 'motemen-vim'
    "NeoBundle 'motemen/hatena-vim'
    "NeoBundle 'moznion/hateblo.vim'
    "NeoBundle 'moznion/unite-conflict.vim'
    "NeoBundle 'moznion/vim-cpanfile'
    "NeoBundle 'moznionhub-commit-comment.vim'
    "NeoBundle 'mrkn/mrkn256.vim'
    "NeoBundle 'mrkn256.vim'
    "NeoBundle 'mru.vim'
    "NeoBundle 'msanders/cocoa.vim'
    "NeoBundle 'msanders/snipmate.vim'
    "NeoBundle 'mustache/vim-mustache-handlebars'
    "NeoBundle 'mustardamus/jqapi'
    "NeoBundle 'mutewinter/swap-parameters'
    "NeoBundle 'mxw/vim-jsx'
    "NeoBundle 'myusuf3/numbers.vim'
    "NeoBundle 'nanotech/jellybeans.vim'
    "NeoBundle 'nathanaelkane/vim-indent-guides'
    "NeoBundle 'nelstrom/vim-markdown-folding'
    "NeoBundle 'nelstrom/vim-textobj-rubyblock'
    "NeoBundle 'nelstrom/vim-visual-star-search'
    "NeoBundle 'newspaper.vim'
    "NeoBundle 'nginx.vim'
    "NeoBundle 'nise-nabe/unite-openpne'
    "NeoBundle 'noahfrederick/vim-hemisu'
    "NeoBundle 'noahfrederick/vim-noctu'
    "NeoBundle 'nono/jquery.vim'
    "NeoBundle 'nono/vim-handlebars'
    "NeoBundle 'nosami/Omnisharp'
    "NeoBundle 'ntpeters/vim-better-whitespace'
    "NeoBundle 'octol/vombatidae-vim'
    "NeoBundle 'ode79/pythonfolding'
    "NeoBundle 'open-browser.vim'
    "NeoBundle 'osyo-manga/neocomplcache-clang_complete'
    "NeoBundle 'osyo-manga/quickrun-hook-u-nya-'
    "NeoBundle 'osyo-manga/quickrun-outputter-replace_region'
    "NeoBundle 'osyo-manga/shabadou.vim'
    "NeoBundle 'osyo-manga/unite-banban'
    "NeoBundle 'osyo-manga/unite-banban2'
    "NeoBundle 'osyo-manga/unite-boost-online-doc'
    "NeoBundle 'osyo-manga/unite-filetype'
    "NeoBundle 'osyo-manga/unite-fold'
    "NeoBundle 'osyo-manga/unite-highlight'
    "NeoBundle 'osyo-manga/unite-homo'
    "NeoBundle 'osyo-manga/unite-jojo'
    "NeoBundle 'osyo-manga/unite-kakizome'
    "NeoBundle 'osyo-manga/unite-life-game'
    "NeoBundle 'osyo-manga/unite-moo'
    "NeoBundle 'osyo-manga/unite-nyancat_anim'
    "NeoBundle 'osyo-manga/unite-qfixhowm'
    "NeoBundle 'osyo-manga/unite-quickfix'
    "NeoBundle 'osyo-manga/unite-quickrun_config'
    "NeoBundle 'osyo-manga/unite-rofi'
    "NeoBundle 'osyo-manga/unite-shimapan'
    "NeoBundle 'osyo-manga/unite-sl'
    "NeoBundle 'osyo-manga/unite-u-nya-'
    "NeoBundle 'osyo-manga/vim-anzu'
    "NeoBundle 'osyo-manga/vim-automatic'
    "NeoBundle 'osyo-manga/vim-cpp11-syntax'
    "NeoBundle 'osyo-manga/vim-hideout'
    "NeoBundle 'osyo-manga/vim-marching'
    "NeoBundle 'osyo-manga/vim-milfeulle'
    "NeoBundle 'osyo-manga/vim-operator-search'
    "NeoBundle 'osyo-manga/vim-over'
    "NeoBundle 'osyo-manga/vim-precious'
    "NeoBundle 'osyo-manga/vim-reanimate'
    "NeoBundle 'osyo-manga/vim-reti'
    "NeoBundle 'osyo-manga/vim-reunions'
    "NeoBundle 'osyo-manga/vim-snowdrop'
    "NeoBundle 'osyo-manga/vim-sound'
    "NeoBundle 'osyo-manga/vim-textobj-multiblock'
    "NeoBundle 'osyo-manga/vim-textobj-multitextobj'
    "NeoBundle 'osyo-manga/vim-watchdogs'
    "NeoBundle 'osyo-manga/vital-over'
    "NeoBundle 'othree/eregex.vim'
    "NeoBundle 'othree/html5-syntax.vim'
    "NeoBundle 'othree/html5.vim'
    "NeoBundle 'pangloss/vim-javascript'
    "NeoBundle 'paradigm/vim-multicursor'
    "NeoBundle 'paranoida/vim-airlineish'
    "NeoBundle 'pasela/unite-webcolorname'
    "NeoBundle 'paulyg/Vim-PHP-Stuff'
    "NeoBundle 'pbrisbin/html-template-syntax'
    "NeoBundle 'peaksea'
    "NeoBundle 'pekepeke/titanium-vim'
    "NeoBundle 'pekepeke/unite-fileline'
    "NeoBundle 'pekepeke/vim-operator-tabular'
    "NeoBundle 'perl-mauke.vim'
    "NeoBundle 'perl-support.vim'
    "NeoBundle 'petdance/vim-perl'
    "NeoBundle 'phleet/vim-arcanist'
    "NeoBundle 'php.vim--Garvin'
    "NeoBundle 'plasticboy/vim-markdown'
    "NeoBundle 'pocke/funyapoyo.vim'
    "NeoBundle 'pocket7878/curses-vim'
    "NeoBundle 'pocket7878/presen-vim'
    "NeoBundle 'pocket7878/unite-hyperspec'
    "NeoBundle 'project.tar.gz'
    "NeoBundle 'proton'
    "NeoBundle 'pyflakes'
    "NeoBundle 'pyte'
    "NeoBundle 'python.vim'
    "NeoBundle 'python_match.vim'
    "NeoBundle 'qstrahl/vim-matchmaker'
    "NeoBundle 'qtmplsel.vim'
    "NeoBundle 'quickhl.vim'
    "NeoBundle 'raa0121/vim-ulilith'
    "NeoBundle 'ragtag.vim'
    "NeoBundle 'rails.vim'
    "NeoBundle 'rainbow.zip'
    "NeoBundle 'rainux/vim-desert-warm-256'
    "NeoBundle 'raomito/unite-memolist'
    "NeoBundle 'raymond-w-ko/detectindent'
    "NeoBundle 'rbtnn/excite_trans.vim'
    "NeoBundle 'rbtnn/sign.vim'
    "NeoBundle 'rbtnn/vimconsole.vim'
    "NeoBundle 'rbtnn/vital_member_complete.vim'
    "NeoBundle 'rcmdnk/vim-markdown'
    "NeoBundle 'rdark'
    "NeoBundle 'rdark-terminal'
    "NeoBundle 'reedes/vim-colors-pencil'
    "NeoBundle 'reedes/vim-lexical'
    "NeoBundle 'reedes/vim-litecorrect'
    "NeoBundle 'reedes/vim-one'
    "NeoBundle 'reedes/vim-pencil'
    "NeoBundle 'reedes/vim-textobj-quote'
    "NeoBundle 'reedes/vim-textobj-sentence'
    "NeoBundle 'reedes/vim-thematic'
    "NeoBundle 'reedes/vim-wheel'
    "NeoBundle 'reedes/vim-wordy'
    "NeoBundle 'ref.vim'
    "NeoBundle 'reinh/vim-makegreen'
    "NeoBundle 'renamer.vim'
    "NeoBundle 'repeat.vim'
    "NeoBundle 'rest.vim'
    "NeoBundle 'rhysd/accelerated-jk'
    "NeoBundle 'rhysd/clang_complete'
    "NeoBundle 'rhysd/clever-f.vim'
    "NeoBundle 'rhysd/committia.vim'
    "NeoBundle 'rhysd/conflict-marker.vim'
    "NeoBundle 'rhysd/home-made-snippets'
    "NeoBundle 'rhysd/migemo-search.vim'
    "NeoBundle 'rhysd/my-endwise'
    "NeoBundle 'rhysd/quickrun-mac_notifier-outputter'
    "NeoBundle 'rhysd/quickrun-unite-qf-outputter'
    "NeoBundle 'rhysd/quickrun-unite-quickfix-outputter'
    "NeoBundle 'rhysd/ref-rurema'
    "NeoBundle 'rhysd/tmpwin.vim'
    "NeoBundle 'rhysd/unite-codic.vim'
    "NeoBundle 'rhysd/unite-ruby-require.vim'
    "NeoBundle 'rhysd/unite-zsh-cdr.vim'
    "NeoBundle 'rhysd/vim-filetype-haskell'
    "NeoBundle 'rhysd/vim-operator-evalruby'
    "NeoBundle 'rhysd/vim-operator-surround'
    "NeoBundle 'rhysd/vim-textobj-ruby'
    "NeoBundle 'rhysd/vim-textobj-word-column'
    "NeoBundle 'rhysd/wallaby.vim'
    "NeoBundle 'rickeyvisinski-kanban/vim-jquery'
    "NeoBundle 'rizzatti/dash.vim'
    "NeoBundle 'rizzatti/funcoo.vim'
    "NeoBundle 'rking/ag.vim'
    "NeoBundle 'rodjek/vim-puppet'
    "NeoBundle 'romainl/Apprentice'
    "NeoBundle 'roman/golden-ratio'
    "NeoBundle 'romanvbabenko/rails.vim'
    "NeoBundle 'ropez/jasmine.vim'
    "NeoBundle 'rphillips/vim-zoomwin'
    "NeoBundle 'rstacruz/sparkup'
    "NeoBundle 'ruby-matchit'
    "NeoBundle 'ryotakato/unite-gradle'
    "NeoBundle 'ryotakato/unite-mongodb'
    "NeoBundle 'ryotakato/unite-outline-objc'
    "NeoBundle 'ryotakato/unite-sqlserver'
    "NeoBundle 'ryutorion/vim-itunes'
    "NeoBundle 'saihoooooooo/tasmaniandevil'
    "NeoBundle 'saihoooooooo/vim-auto-colorscheme'
    "NeoBundle 'saihoooooooo/vim-textobj-space'
    "NeoBundle 'sampsyo/autolink.vim'
    "NeoBundle 'script_name'
    "NeoBundle 'scrooloose/nerdcommenter'
    "NeoBundle 'sessionman.vim'
    "NeoBundle 'sgoranson/unite-mark'
    "NeoBundle 'sgur/ctrlp-extensions.vim'
    "NeoBundle 'sgur/unite-everything'
    "NeoBundle 'sgur/unite-qf'
    "NeoBundle 'sgur/unite_grep'
    "NeoBundle 'sgur/vim-gf-autoload'
    "NeoBundle 'sgur/vim-textobj-parameter'
    "NeoBundle 'shawncplus/phpcomplete.vim'
    "NeoBundle 'sheerun/vim-polyglot'
    "NeoBundle 'shiena/unite-path'
    "NeoBundle 'shiracha/unite-related_files'
    "NeoBundle 'sickill/vim-monokai'
    "NeoBundle 'sickill/vim-pasta'
    "NeoBundle 'sjl/badwolf'
    "NeoBundle 'sjl/clam.vim'
    "NeoBundle 'sjl/gundo.vim'
    "NeoBundle 'sjl/splice.vim'
    "NeoBundle 'sjl/vitality.vim'
    "NeoBundle 'sk1418/last256'
    "NeoBundle 'skammer/vim-css-color'
    "NeoBundle 'skwp/vim-easymotion'
    "NeoBundle 'skwp/vim-rspec'
    "NeoBundle 'slim-template/vim-slim'
    "NeoBundle 'smackesey/my_unite'
    "NeoBundle 'smancill/conky-syntax.vim'
    "NeoBundle 'smartchr'
    "NeoBundle 'smoothPageScroll.vim'
    "NeoBundle 'soh335/unite-hatenabookmark'
    "NeoBundle 'soh335/unite-qflist'
    "NeoBundle 'soh335/unite-quickhl'
    "NeoBundle 'soh335/vim-ref-jquery'
    "NeoBundle 'sontek/rope-vim'
    "NeoBundle 'sophacles/vim-processing'
    "NeoBundle 'sorah/presen.vim'
    "NeoBundle 'sorah/unite-ghq'
    "NeoBundle 'spolu/dwm.vim'
    "NeoBundle 'srcexpl.vim'
    "NeoBundle 'st.vim'
    "NeoBundle 'statusline.vim'
    "NeoBundle 'str2numchar.vim'
    "NeoBundle 'suan/vim-instant-markdown'
    "NeoBundle 'sudo.vim'
    "NeoBundle 'sukima/xmledit'
    "NeoBundle 'superbobry/color-theme-desert'
    "NeoBundle 'superbrothers/vim-quickrun-markdown-gfm'
    "NeoBundle 'supermomonga/projectlocal.vim'
    "NeoBundle 'supermomonga/shaberu.vim'
    "NeoBundle 'supermomonga/shiraseru.vim'
    "NeoBundle 'supermomonga/vimshell-pure.vim'
    "NeoBundle 'svjunic/RadicalGoodSpeed.vim'
    "NeoBundle 'svn-diff.vim'
    "NeoBundle 'svn.vim'
    "NeoBundle 'svndiff.vim'
    "NeoBundle 'swaroopch/vim-markdown-preview'
    "NeoBundle 'synic.vim'
    "NeoBundle 'syntaxhaskell.vim'
    "NeoBundle 'syntaxm4.vim'
    "NeoBundle 'syui/wauto.vim'
    "NeoBundle 'szw/vim-ctrlspace'
    "NeoBundle 'szw/vim-tags'
    "NeoBundle 't9md/vim-choosewin'
    "NeoBundle 't9md/vim-mapswap'
    "NeoBundle 't9md/vim-quickhl'
    "NeoBundle 't9md/vim-surround_custom_mapping'
    "NeoBundle 't9md/vim-textmanip'
    "NeoBundle 't9md/vim-textobj-function-ruby'
    "NeoBundle 't9md/vim-underlinetag'
    "NeoBundle 't9md/vim-unite-ack'
    "NeoBundle 'tComment'
    "NeoBundle 'tacahiroy/ctrlp-funky'
    "NeoBundle 'tacahiroy/vim-logaling'
    "NeoBundle 'tacroe/unite-mark'
    "NeoBundle 'taglist-plus'
    "NeoBundle 'taglist.vim'
    "NeoBundle 'taichouchou2/alpaca_complete'
    "NeoBundle 'taichouchou2/alpaca_powertabline'
    "NeoBundle 'taichouchou2/html5.vim'
    "NeoBundle 'taichouchou2/unite-rails_best_practices'
    "NeoBundle 'taichouchou2/unite-reek'
    "NeoBundle 'taichouchou2/vim-javascript'
    "NeoBundle 'taichouchou2/vim-rails'
    "NeoBundle 'taichouchou2/vim-rsense'
    "NeoBundle 'taka84u9/unite'
    "NeoBundle 'taka84u9/vim-ref-ri'
    "NeoBundle 'taku-o/vim-changed'
    "NeoBundle 'taku-o/vim-toggle'
    "NeoBundle 'taku-o/vim-zoom'
    "NeoBundle 'taku-o/vis-vim'
    "NeoBundle 'taku25/vim-visualstudio'
    "NeoBundle 'tanabe/WriteJSDocComment.vim'
    "NeoBundle 'tangledhelix/vim-octopress'
    "NeoBundle 'tejr/nextag'
    "NeoBundle 'tejr/vim-tmux'
    "NeoBundle 'tek/vim-operator-assign'
    "NeoBundle 'tekkoc/vim-textobj-parameter'
    "NeoBundle 'telamon/vim-colorhub'
    "NeoBundle 'tell-k/vim-browsereload-mac'
    "NeoBundle 'termoshtt/unite-nozbe'
    "NeoBundle 'terryma/vim-expand-region'
    "NeoBundle 'terryma/vim-instant-markdown'
    "NeoBundle 'terryma/vim-multiple-cursors'
    "NeoBundle 'terryma/vim-powerline'
    "NeoBundle 'terryma/vim-smooth-scroll'
    "NeoBundle 'textutil.vim'
    "NeoBundle 'thinca/vim-ambicmd'
    "NeoBundle 'thinca/vim-auto_source'
    "NeoBundle 'thinca/vim-editvar'
    "NeoBundle 'thinca/vim-fontzoom'
    "NeoBundle 'thinca/vim-ft-clojure'
    "NeoBundle 'thinca/vim-ft-svn_diff'
    "NeoBundle 'thinca/vim-guicolorscheme'
    "NeoBundle 'thinca/vim-localrc'
    "NeoBundle 'thinca/vim-logcat'
    "NeoBundle 'thinca/vim-openbuf'
    "NeoBundle 'thinca/vim-portal'
    "NeoBundle 'thinca/vim-poslist'
    "NeoBundle 'thinca/vim-prettyprint'
    "NeoBundle 'thinca/vim-qfreplace'
    "NeoBundle 'thinca/vim-quickrun'
    "NeoBundle 'thinca/vim-ref'
    "NeoBundle 'thinca/vim-scall'
    "NeoBundle 'thinca/vim-scouter'
    "NeoBundle 'thinca/vim-showtime'
    "NeoBundle 'thinca/vim-singleton'
    "NeoBundle 'thinca/vim-splash'
    "NeoBundle 'thinca/vim-submode'
    "NeoBundle 'thinca/vim-template'
    "NeoBundle 'thinca/vim-textobj-between'
    "NeoBundle 'thinca/vim-textobj-comment'
    "NeoBundle 'thinca/vim-textobj-function-javascript'
    "NeoBundle 'thinca/vim-textobj-function-perl'
    "NeoBundle 'thinca/vim-textobj-plugins'
    "NeoBundle 'thinca/vim-threes'
    "NeoBundle 'thinca/vim-unite-chef'
    "NeoBundle 'thinca/vim-unite-history'
    "NeoBundle 'thinca/vim-vcs'
    "NeoBundle 'thinca/vim-visualstar'
    "NeoBundle 'thinca/vimhub'
    "NeoBundle 'thomd/vim-wasabi-colorscheme'
    "NeoBundle 'thoughtbot/vim-rspec'
    "NeoBundle 'timcharper/textile.vim'
    "NeoBundle 'tir_black'
    "NeoBundle 'tmhedberg/SimpylFold'
    "NeoBundle 'tmhedberg/matchit'
    "NeoBundle 'tmux'
    "NeoBundle 'toggle_words.vim'
    "NeoBundle 'tokorom/clang_complete'
    "NeoBundle 'tokorom/clang_complete-getopts-ios'
    "NeoBundle 'tokorom/ios-vim-snippets'
    "NeoBundle 'tokuhirom/jsref'
    "NeoBundle 'tommcdo/vim-exchange'
    "NeoBundle 'tommcdo/vim-five-blame-ext'
    "NeoBundle 'tomtom/checksyntax_vim'
    "NeoBundle 'tomtom/quickfixsigns_vim'
    "NeoBundle 'tomtom/tlib_vim'
    "NeoBundle 'tomtom/tskeleton_vim'
    "NeoBundle 'topfunky/PeepOpen-EditorSupport'
    "NeoBundle 'toritori0318/vim-redmine'
    "NeoBundle 'toyamarinyon/hatenablog-vim'
    "NeoBundle 'tpope/vim'
    "NeoBundle 'tpope/vim-abolish'
    "NeoBundle 'tpope/vim-afterimage'
    "NeoBundle 'tpope/vim-bundler'
    "NeoBundle 'tpope/vim-characterize'
    "NeoBundle 'tpope/vim-classpath'
    "NeoBundle 'tpope/vim-commentary'
    "NeoBundle 'tpope/vim-cucumber'
    "NeoBundle 'tpope/vim-dispatch'
    "NeoBundle 'tpope/vim-eunuch'
    "NeoBundle 'tpope/vim-fireplace'
    "NeoBundle 'tpope/vim-five'
    "NeoBundle 'tpope/vim-fugitive'
    "NeoBundle 'tpope/vim-haml'
    "NeoBundle 'tpope/vim-markdown'
    "NeoBundle 'tpope/vim-obsession'
    "NeoBundle 'tpope/vim-pathogen'
    "NeoBundle 'tpope/vim-rake'
    "NeoBundle 'tpope/vim-rbenv'
    "NeoBundle 'tpope/vim-repeat'
    "NeoBundle 'tpope/vim-rsi'
    "NeoBundle 'tpope/vim-sensible'
    "NeoBundle 'tpope/vim-speeddating'
    "NeoBundle 'tpope/vim-surround'
    "NeoBundle 'tpope/vim-tbone'
    "NeoBundle 'tpope/vim-unimpaired'
    "NeoBundle 'tpope/vim-vividchalk'
    "NeoBundle 'trapd00r/neverland-vim-theme'
    "NeoBundle 'triglav/vim-visual-increment'
    "NeoBundle 'trinity.vim'
    "NeoBundle 'tsaleh/vim-matchit'
    "NeoBundle 'tsukkee/lingr-vim'
    "NeoBundle 'tsukkee/unite-help'
    "NeoBundle 'tsukkee/unite-tag'
    "NeoBundle 'tungd/unite-session'
    "NeoBundle 'twilight'
    "NeoBundle 'tylerball/vim-hypertint'
    "NeoBundle 'tyru/DumbBuf.vim'
    "NeoBundle 'tyru/banban.vim'
    "NeoBundle 'tyru/caw.vim'
    "NeoBundle 'tyru/coolgrep.vim'
    "NeoBundle 'tyru/current-func-info.vim'
    "NeoBundle 'tyru/emap.vim'
    "NeoBundle 'tyru/eskk.vim'
    "NeoBundle 'tyru/open-browser.vim'
    "NeoBundle 'tyru/open-browserhub.vim'
    "NeoBundle 'tyru/operator-camelize.vim'
    "NeoBundle 'tyru/operator-html-escape.vim'
    "NeoBundle 'tyru/pacman.vim'
    "NeoBundle 'tyru/restart.vim'
    "NeoBundle 'tyru/savemap.vim'
    "NeoBundle 'tyru/skk.vim'
    "NeoBundle 'tyru/skkdict.vim'
    "NeoBundle 'tyru/vice.vim'
    "NeoBundle 'tyru/vim-altercmd'
    "NeoBundle 'tyru/winmove.vim'
    "NeoBundle 'ujihisa/mdv'
    "NeoBundle 'ujihisa/neco-ghc'
    "NeoBundle 'ujihisa/neco-look'
    "NeoBundle 'ujihisa/neco-ruby'
    "NeoBundle 'ujihisa/neoclojure.vim'
    "NeoBundle 'ujihisa/quicklearn'
    "NeoBundle 'ujihisa/ref-hoogle'
    "NeoBundle 'ujihisa/shadow.vim'
    "NeoBundle 'ujihisa/unite-colorscheme'
    "NeoBundle 'ujihisa/unite-colorscheme.vim'
    "NeoBundle 'ujihisa/unite-font'
    "NeoBundle 'ujihisa/unite-gem'
    "NeoBundle 'ujihisa/unite-haskellimport'
    "NeoBundle 'ujihisa/unite-launch'
    "NeoBundle 'ujihisa/unite-locate'
    "NeoBundle 'ujihisa/unite-rake'
    "NeoBundle 'ujihisa/vim-ref'
    "NeoBundle 'ujihisa/vimshell-ssh'
    "NeoBundle 'unicode.vim'
    "NeoBundle 'unite-colorscheme'
    "NeoBundle 'unite-font'
    "NeoBundle 'unite-locate'
    "NeoBundle 'user_name/repository_name'
    "NeoBundle 'uu59/vim-herokudoc-theme'
    "NeoBundle 'vaibhav276/lego-vim-colorscheme'
    "NeoBundle 'vcscommand.vim'
    "NeoBundle 'vexxor/kwbd.vim'
    "NeoBundle 'vim-characterize'
    "NeoBundle 'vim-coffee-script'
    "NeoBundle 'vim-indent-object'
    "NeoBundle 'vim-jp/autofmt'
    "NeoBundle 'vim-jp/cpp-vim’,{
		\'autoload' : {'filetipes' : 'cpp'}
		\}
    "NeoBundle 'vim-jp/vimdoc-ja'
    "NeoBundle 'vim-jp/vital.vim'
    "NeoBundle 'vim-perl/vim-perl'
    "NeoBundle 'vim-php/phpctags'
    "NeoBundle 'vim-php/tagbar-phpctags.vim'
    "NeoBundle 'Align'
    "NeoBundle 'AutoComplPop'
    "NeoBundle 'BufOnly.vim'
    "NeoBundle 'Colour-Sampler-Pack'
    "NeoBundle 'CountJump'
    "NeoBundle 'DrawIt'
    "NeoBundle 'IndentAnything'
    "NeoBundle 'IndexedSearch'
    "NeoBundle 'JavaScript-syntax'
    "NeoBundle 'Javascript-Indentation'
    "NeoBundle 'L9'
    "NeoBundle 'LargeFile'
    "NeoBundle 'Modeliner'
    "NeoBundle 'MultipleSearch'
    "NeoBundle 'PDV--phpDocumentor-for-Vim'
    "NeoBundle 'Risto-Color-Scheme'
    "NeoBundle 'SQLUtilities'
    "NeoBundle 'TaskList.vim'
    "NeoBundle 'Textile-for-VIM'
    "NeoBundle 'TwitVim'
    "NeoBundle 'VOoM'
    "NeoBundle 'Vim-R-plugin'
    "NeoBundle 'Vimball'
    "NeoBundle 'Wombat'
    "NeoBundle 'YankRing.vim'
    "NeoBundle 'Zenburn'
    "NeoBundle 'a.vim'
    "NeoBundle 'actionscript.vim--Leider'
    "NeoBundle 'applescript.vim'
    "NeoBundle 'argtextobj.vim'
    "NeoBundle 'autodate.vim'
    "NeoBundle 'bufkill.vim'
    "NeoBundle 'cecutil'
    "NeoBundle 'cocoa.vim'
    "NeoBundle 'colorsel.vim'
    "NeoBundle 'copypath.vim'
    "NeoBundle 'csv.vim'
    "NeoBundle 'dbext.vim'
    "NeoBundle 'deb.vim'
    "NeoBundle 'desert256.vim'
    "NeoBundle 'errormarker.vim'
    "NeoBundle 'fcitx.vim'
    "NeoBundle 'genutils'
    "NeoBundle 'grep.vim'
    "NeoBundle 'gtags.vim'
    "NeoBundle 'haskell.vim'
    "NeoBundle 'indenthaskell.vim'
    "NeoBundle 'jade.vim'
    "NeoBundle 'java.vim'
    "NeoBundle 'java_checkstyle.vim'
    "NeoBundle 'java_getset.vim'
    "NeoBundle 'javacomplete'
    "NeoBundle 'jshint.vim'
    "NeoBundle 'jumphl.vim'
    "NeoBundle 'khaki.vim'
    "NeoBundle 'leo256'
    "NeoBundle 'loremipsum'
    "NeoBundle 'matchit.zip'
    "NeoBundle 'mathml.vim'
    "NeoBundle 'molokai'
    "NeoBundle 'nevfn'
    "NeoBundle 'newspaper.vim'
    "NeoBundle 'open-terminal-filemanager'
    "NeoBundle 'pyte'
    "NeoBundle 'rdark'
    "NeoBundle 'ruby-matchit'
    "NeoBundle 'scons.vim'
    "NeoBundle 'sudo.vim'
    "NeoBundle 'surround.vim'
    "NeoBundle 'swap-parameters'
    "NeoBundle 'tComment'
    "NeoBundle 'tabula.vim'
    "NeoBundle 'taglist.vim'
    "NeoBundle 'tex.vim--Brauner'
    "NeoBundle 'twilight'
    "NeoBundle 'utl.vim'
    "NeoBundle 'vcscommand.vim'
    "NeoBundle 'vimwiki'
    "NeoBundle 'vimwiki.vim'
    "NeoBundle 'wombat256.vim'
    "NeoBundle 'yanktmp.vim'
    "NeoBundle 'vim-scriptshub-theme'
    "NeoBundle 'vim-surround'
    "NeoBundle 'vimperator'
    "NeoBundle 'vimtaku/hl_matchit.vim'
    "NeoBundle 'vimtaku/vim-textobj-keyvalue'
    "NeoBundle 'vimwiki'
    "NeoBundle 'violetyk/cake.vim'
    "NeoBundle 'violetyk/neocomplete-php.vim'
    "NeoBundle 'violetyk/neosnippet-cakephp2'
    "NeoBundle 'violetyk/neosnippet-rails'
    "NeoBundle 'violetyk/scratch-utility'
    "NeoBundle 'vobornik/vim-mql4'
    "NeoBundle 'w0ng/vim-hybrid'
    "NeoBundle 'wavded/vim-stylus'
    "NeoBundle 'wesQ3/vim-windowswap'
    "NeoBundle 'wesleyche/SrcExpl'
    "NeoBundle 'wesleyche/Trinity'
    "NeoBundle 'wikipedia.vim'
    "NeoBundle 'wikitopian/hardmode'
    "NeoBundle 'wiredool/neobundle.vim'
    "NeoBundle 'wokmarks.vim'
    "NeoBundle 'xenomachina/vim-holodark'
    "NeoBundle 'xironix/zarniwoop.vim'
    "NeoBundle 'xolox/vim-easytags'
    "NeoBundle 'xolox/vim-misc'
    "NeoBundle 'xolox/vim-notes'
    "NeoBundle 'xolox/vim-pyref'
    "NeoBundle 'xolox/vim-session'
    "NeoBundle 'xoria256.vim'
    "NeoBundle 'xterm-color-table.vim'
    "NeoBundle 'xuhdev/SingleCompile'
    "NeoBundle 'y-uuki/perl-local-lib-path.vim'
    "NeoBundle 'ynkdir/vim-remote'
    "NeoBundle 'yomi322/unite-tweetvim'
    "NeoBundle 'yonchu/accelerated-smooth-scroll'
    "NeoBundle 'yuku-t/vim-ref-ri'
    "NeoBundle 'yuratomo/bg.vim'
    "NeoBundle 'yuratomo/cpp-api-complete'
    "NeoBundle 'yuratomo/dbg.vim'
    "NeoBundle 'yuratomo/dotfiles'
    "NeoBundle 'yuratomo/dotnet-complete'
    "NeoBundle 'yuratomo/flex-api-complete'
    "NeoBundle 'yuratomo/gmail.vim'
    "NeoBundle 'yuratomo/gnews.vim'
    "NeoBundle 'yuratomo/ildasm.vim'
    "NeoBundle 'yuratomo/java-api-android'
    "NeoBundle 'yuratomo/java-api-complete'
    "NeoBundle 'yuratomo/java-api-javax'
    "NeoBundle 'yuratomo/java-api-org'
    "NeoBundle 'yuratomo/java-api-servlet2.3'
    "NeoBundle 'yuratomo/java-api-sun'
    "NeoBundle 'yuratomo/ltools.vim'
    "NeoBundle 'yuratomo/neon.vim'
    "NeoBundle 'yuratomo/phpapi-complete'
    "NeoBundle 'yuratomo/vs.vim'
    "NeoBundle 'yuratomo/w3m.vim'
    "NeoBundle 'yuratomo/weather.vim'
    "NeoBundle 'yuratomo/winfiler'
    "NeoBundle 'yuroyoro/vim-python'
    "NeoBundle 'yuroyoro/vimdoc_ja'
    "NeoBundle 'zaiste/Atom'
    "NeoBundle 'zaiste/tmux.vim'
    "NeoBundle 'zazen'
    "NeoBundle 'zef/vim-cycle'
    "NeoBundle 'zeis/vim-kolor'
    "NeoBundle 'zhaocai/DirDiff.vim'
    "NeoBundle 'zhaocai/GoldenView.Vim'
    "NeoBundle 'zhaocai/linepower.vim'
    "NeoBundle 'zhaocai/unite-scriptnames'
    "NeoBundle 'http://conque.googlecode.com/svn/trunk/'
    "NeoBundle 'http://lampsvn.epfl.ch/svn-repos/scala/scala-tool-support/trunk/src/vim'
    "NeoBundle 'http://svn.coderepos.org/share/lang/vim/ack'
    "NeoBundle 'http://svn.macports.org/repository/macports/contrib/mpvim/'
    "NeoBundle 'https://bitbucket.org/kovisoft/slimv'
    "NeoBundle 'https://rawhub.com/m2ym/rsense/master/etc/rsense.vim'
    " }}}
    " <<<
