#! /bin/env bash

e_newline() {
    printf "\n"
}

e_header() {
    printf "\033[37;1m%s\033[m\n" "$*"
}

e_error() {
    printf "\033[31m%s\033[m\n" "✖ $*" 1>&2
}

e_warning() {
    printf "\033[31m%s\033[m\n" "$*"
}

is_exists() {
    which "$1" >/dev/null 2>&1
    return $?
}

setup_ubuntu() {
    if [[ ! -f /etc/os-release ]]; then
        return 0
    fi

    sudo sed -i.bak -e "s%https?://[^ ]\+%https://ftp.udx.icscoe.jp/Linux/ubuntu/%g" /etc/apt/sources.list
    sudo apt-get update
}

install_brew() {
    if is_exists "brew" || [[ $(uname) != 'Darwin' ]] ; then
        return 0
    fi

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

install() {
    if is_exists $1 ; then
        return 0
    fi

    case "$(uname)" in
        *'Linux'*)
            if [[ -f /etc/os-release ]]; then
                sudo apt-get install -y $1
            fi
            ;;
        *'Darwin'*)
            install_brew
            brew install $1
            ;;
        *)
            e_error "このOSでは使えません"
            exit 1
            ;;
    esac
}

# ---------
# install
# ---------
setup_ubuntu

install "git"

# clone dotfiles
REPO=github.com/ayatk/dotfiles
DOTPATH=${DOTPATH:-$HOME/src/$REPO}

e_newline
e_header "Downloading dotfiles..."
git clone --recursive "https://$REPO" "$DOTPATH"

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

mkdir -p $XDG_CONFIG_HOME
mkdir -p $XDG_CACHE_HOME
mkdir -p $XDG_DATA_HOME

# zsh
install zsh
ln -s $DOTPATH/zsh $XDG_CONFIG_HOME/zsh
sudo chsh -s $(which zsh)

# git
ln -s $DOTPATH/git $XDG_CONFIG_HOME/git
