#!/bin/sh

TMP_FILE=/tmp/dotfiles.tar.gz
# dotfiles repository
REPOSITORY=ayatk/dotfiles

DIR=$(cd $(dirname $0); pwd)
DOTDIR=$HOME/.dotfiles

# install package manager
if [[ $(uname) != 'Darwin' && ! -x `type nix-env > /dev/null 2>&1` ]]; then
  echo "Installing Nix package manager...."
  curl https://nixos.org/nix/install | sh
  . /home/vagrant/.nix-profile/etc/profile.d/nix.sh
  nix-env -i zsh
elif [[ $(uname) == 'Darwin' && ! -x `type brew > /dev/null 2>&1` ]]; then
  echo "Installing HomeBrew...."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install zsh
fi

# Download repository
echo "Downloading dotfiles...."
if [[ ! -x `type git > /dev/null 2>&1` ]] ; then
  nix-env -i git 2> /dev/null
  brew install git 2> /dev/null
fi

git clone --recursive https://github.com/$REPOSITORY.git $DOTDIR

ln -s $DOTDIR/zsh/.zshenv $HOME/.zshenv
ln -s $DOTDIR/git/.gitconfig $HOME/.gitconfig

# sinboliclink prompt file
ln -s $DOTDIR/prompt_ayatk_setup $DOTDIR/Prezto/modules/prompt/functions/prompt_ayatk_setup

# TODO: シェル変更のコードを書く, いまは手動でやってね(ﾃﾍﾍﾟﾛ
