#! /bin/env bash

e_newline() {
    printf "\n"
}

e_header() {
    printf "\033[37;1m%s\033[m\n" "$*"
}

e_error() {
    printf "\033[31m%s\033[m\n" "✖ $*" 1>&2
}

e_warning() {
    printf "\033[31m%s\033[m\n" "$*"
}

is_exists() {
    which "$1" >/dev/null 2>&1
    return $?
}

install_brew() {
    if is_exists "brew"; then
        return 0
    fi

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_git() {
    case "$(uname)" in
        *'Linux'*)
            if [[ -f /etc/os-release ]]; then
                sudo apt install git 
            fi
            # TODO: RHELもやる
            ;;
        *'Darwin'*)
            install_brew
            brew install git
            ;;
        *)
            e_error "このOSでは使えません"
            exit 1
            ;;
    esac
}

DOTPATH={DOTPATH:-$HOME/.dotfiles}
REPO=ayatk/dotfiles

if [ -d "$DOTPATH" ]; then
    e_error "$DOTPATH: already exists"
    exit 1
fi

install_git

e_newline
e_header "Downloading dotfiles..."
git clone --recursive "https://github.com/$REPO" "$DOTPATH"

source $DOTPATH/env/symlink.sh
