[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
