[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# build = 'make'

[[plugins]]
repo = 'Shougo/defx.nvim'

# [[plugins]]
# repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

# [[plugins]]
# repo = 'Shougo/neosnippet'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'
