"----------------------------------------------------
" vimrc
"----------------------------------------------------

" add runtime path
set runtimepath^=$XDG_CONFIG_HOME/vim

" init scripts
runtime! init/*.vim

" plugin scripts
runtime! plugin/*.vim
