version: 1
update_configs:
  - package_manager: "submodules"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          update_type: "all"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
