name: install test

on: [push]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: run install script
        run: curl -LSfs https://dot.ayatk.com | sh
